package MySQL;
//보호소에서 중성화한 동물
public class Programmers59045 {
//	SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME,A.SEX_UPON_INTAKE
//	FROM ANIMAL_INS A
//	JOIN ANIMAL_OUTS B
//	ON A.ANIMAL_ID = B.ANIMAL_ID
//	WHERE (A.SEX_UPON_INTAKE like 'Spayed Female')
//	ORDER BY ANIMAL_ID;
}
